# Generated by Django 6.0.3 on 2026-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('badge_icon', models.CharField(default='🛡️', help_text='Unicode icon emoji (e.g. 🐍, 🛡️, 🔒)', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project (e.g., SYAFRA)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the project engineering features')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', max_length=500, null=True)),
                ('live_url', models.URLField(blank=True, help_text='Live website URL', max_length=500, null=True)),
                ('image', models.CharField(default='static/assets/syafra.png', help_text='Static relative image path (e.g., assets/syafra.png)', max_length=300)),
                ('tags', models.CharField(help_text='Comma-separated technologies (e.g., Python, Django, PostgreSQL)', max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Integer indicating rendering order (lower numbers display first)')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Time period label (e.g., Early 2024)', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
