# Generated by Django 6.0.3 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Upload the certificate image that should appear when this headline is selected.', null=True, upload_to='certificates/'),
        ),
    ]
