# Generated by Django 6.0.3 on 2026-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolioprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Syamraj R Resume', max_length=200)),
                ('description', models.TextField(default="Download Syamraj R's complete curriculum resume detailing CEH certifications, Advanced Diploma specifications, and full Django capabilities.")),
                ('resume_file', models.FileField(help_text='Upload the current resume file recruiters should download.', upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active resume is shown on the portfolio download section.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Upload',
                'verbose_name_plural': 'Resume Uploads',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
